[build]
  base = "frontend"
  command = "yarn install --legacy-peer-deps && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200